<?php
/**
 *
 * Developed by Waizabú <code@waizabu.com>
 *
 *
 */

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add files' => 'Añadir archivos',
    'Add version' => 'Añadir versión',
    'Back' => 'Atrás',
    'Children' => 'Hijos',
    'Created At' => 'Creado',
    'Created By' => 'Creado por',
    'Depth displayed is limited to {limit} in both directions' => 'La profundida está limitada a {limit} en ambas direcciones',
    'Directory' => 'Directorio',
    'Download' => 'Descargar',
    'Extension' => 'Extension',
    'File' => 'Archivo',
    'File ID' => 'Id de Archivo',
    'File does not exists' => 'El archivo no existe',
    'File not found' => 'Archivo no encontrado',
    'File size' => 'Tamaño del archivo',
    'Files catalog' => 'Catálogo de archivos',
    'Go last' => 'Ir a la última',
    'Info' => 'Info',
    'Name' => 'Nombre',
    'New folder' => 'Nueva carpeta',
    'New inode' => 'Nuevo inodo',
    'Open' => 'Abrir',
    'Open parent' => 'Abrir padre',
    'Original' => 'Original',
    'Parent ID' => 'Id del padre',
    'Parents' => 'Padres',
    'Properties' => 'Propiedades',
    'Real path' => 'Ruta real',
    'Symlink' => 'Enlace simbólico',
    'Target not defined' => 'Destino no definido',
    'This document has not versions' => 'Este documento no tiene versiones',
    'This file cannot be displayed online.' => 'Este archivo no se puede mostrar online',
    'This is an older version of the document' => 'Esta es una versión antigua del documento',
    'This item has nested items and cannot be deleted.' => 'Este objeto tiene hijos y no puede ser eliminado',
    'Type' => 'Tipo',
    'Unable to get parent' => 'Imposible obtener el padre',
    'Unable to move file to its destination' => 'Imposible mover el archivo a su destino',
    'Updated At' => 'Actualizado',
    'Version' => 'Versión',
    'Version ID' => 'Id de versión',
    'Versions' => 'Versiones',
    'View' => 'Ver',
    'View contents' => 'Ver contenido',
    'Add' => 'Añadir',
    'ID' => '',
    'MD5 Checksum' => '',
    'Mime' => '',
    'Uuid' => '',
];
