<?php
/**
 *
 * Developed by Waizabú <code@waizabu.com>
 *
 *
 */

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access control' => 'Control de acceso',
    'Add' => 'Añadir',
    'Add files' => 'Añadir archivos',
    'Add permission' => 'Añadir permiso',
    'Add version' => 'Añadir versión',
    'All logged in' => 'Solo con inicio de sesión',
    'Back' => 'Atrás',
    'Cancel' => 'Cancelar',
    'Confirm deletion' => 'Confirmar borrado',
    'Confirm deletion?' => '¿Confirmar borrado?',
    'Created At' => 'Creado',
    'Created By' => 'Creado por',
    'Current permissions' => 'Permisos actuales',
    'Delete' => 'Borrar',
    'Delete directory' => 'Eliminar directorio',
    'Delete only this version' => 'Eliminar sólo esta versión',
    'Delete permanently' => 'Eliminar permanentemente',
    'Directory' => 'Directorio',
    'Download' => 'Descargar',
    'Everyone' => 'Todos',
    'Extension' => 'Extensión',
    'File' => 'Archivo',
    'File ID' => 'Id de Archivo',
    'File does not exists' => 'El archivo no existe',
    'File not found' => 'Archivo no encontrado',
    'File size' => 'Tamaño del archivo',
    'Files catalog' => 'Catálogo de archivos',
    'Go last' => 'Ir a la última',
    'Human name' => 'Nombre humanizado',
    'Info' => 'Info',
    'Name' => 'Nombre',
    'New folder' => 'Nueva carpeta',
    'New inode' => 'Nuevo inodo',
    'Open' => 'Abrir',
    'Open parent' => 'Abrir padre',
    'Original' => 'Original',
    'Parent ID' => 'Id del padre',
    'Permissions are for the original and all versions.' => 'Los permisos son para el original y sus versiones',
    'Properties' => 'Propiedades',
    'Read' => 'Leer',
    'Real path' => 'Ruta real',
    'Role' => 'Rol',
    'Root node can not be deleted' => 'El nodo principal no puede ser eliminado',
    'Symlink' => 'Enlace simbólico',
    'Target not defined' => 'Destino no definido',
    'This are the properties of this file version.' => 'Estas son las propiedades de esta versión',
    'This document has not versions' => 'Este documento no tiene versiones',
    'This file cannot be displayed online.' => 'Este archivo no se puede mostrar online',
    'This is an older version of the document' => 'Esta es una versión antigua del documento',
    'This operation can not be undone' => 'Esta operación no se puede deshacer',
    'This permission is already assigned' => 'Este permiso ya está asignado',
    'To delete this folder and all its contents, write the first {nchar} characters of directory name' => 'Para eliminar este directorio y todos sus contenidos, escriba los {nchar} primeros caracteres del nombre del directorio',
    'Type' => 'Tipo',
    'Unable to get parent' => 'Imposible obtener el padre',
    'Unable to move file to its destination' => 'Imposible mover el archivo a su destino',
    'Update' => 'Editar',
    'Updated At' => 'Actualizado',
    'User' => 'Usuario',
    'Version' => 'Versión',
    'Version ID' => 'Id de versión',
    'Versions' => 'Versiones',
    'View' => 'Ver',
    'View contents' => 'Ver contenido',
    'View file properties' => 'Ver propiedades del archivo',
    'Wildcards' => 'Comodines',
    'Write' => 'Escribir',
    'by' => 'por',
    'or' => 'ó',
    '{wildcard} allow everyone access to this item.' => '{wildcard} permitirá a cualquiera acceder a este item',
    '{wildcard} allow everyone logged in access to this item.' => '{wildcard} permitirá el acceso sólo a los que iniciaron sesión.',
    'Bulk actions' => 'Acciones en bloque',
    'Bulk delete' => 'Borrado en bloque',
    'Delete all items' => 'Eliminar todos los objetos',
    'ID' => '',
    'Items to be deleted' => 'Objetos a eliminar',
    'MD5 Checksum' => '',
    'Mime' => '',
    'To confirm deletion write the next string in the text input and click confirm' => 'Para confirmar el borrado escriba la siguiente cadena en el campo de texto y haga click en confirmar',
];
